# Generated by Django 3.2.13 on 2022-05-02 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0014_delete_bookreadingrecord'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('dt_updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('reading', 'Сейчас читаю'), ('finished', 'Прочитаны')], default='reading', max_length=255, verbose_name='Статус')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_records', to='bookstore.book', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_records', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Библиотечная запись',
                'verbose_name_plural': 'Библиотечные записи',
            },
        ),
    ]
