# Generated by Django 3.2.13 on 2022-04-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelves', '0001_initial'),
        ('bookstore', '0011_remove_book_dt_release'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(related_name='users', through='bookshelves.UserBook', to='bookstore.Book', verbose_name='Книги пользователя'),
        ),
    ]
