# Generated by Django 3.2.13 on 2022-05-02 18:05

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_libraryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryrecord',
            name='dt_return',
            field=models.DateField(default=profiles.models.get_return_date, verbose_name='Дата возврата книги'),
        ),
    ]
