# Generated by Django 3.2.12 on 2022-04-02 18:20

from django.db import migrations


def create_default_category(apps, schema_editor):
    DEFAULT_CATEGORY = 'Без категории'
    Category = apps.get_model('bookstore', 'Category')
    Category.objects.get_or_create(title=DEFAULT_CATEGORY)


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_category, migrations.RunPython.noop),
    ]
