# Generated by Django 3.2.13 on 2022-04-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='BookSection',
        ),
        migrations.AlterModelOptions(
            name='booksection',
            options={'verbose_name': 'Книжный раздел', 'verbose_name_plural': 'Книжные разделы'},
        ),
        migrations.AddField(
            model_name='book',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookstore.booksection', verbose_name='Книжный раздел'),
        ),
    ]
