# Generated by Django 3.2.13 on 2022-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20220423_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='bookstore/covers/', verbose_name='Обложка'),
        ),
    ]
