# Generated by Django 3.2.13 on 2022-04-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_booksection_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksection',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер раздела'),
        ),
    ]
