# Generated by Django 3.2.13 on 2022-04-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_auto_20220424_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dt_release',
        ),
    ]
