# Generated by Django 3.2.13 on 2022-05-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0013_alter_bookreadingrecord_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReadingRecord',
        ),
    ]
